# Generated by Django 3.1.2 on 2020-12-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20201223_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donecheck', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('1', '1️⃣'), ('2', '2️⃣'), ('3', '3️⃣'), ('4', '4️⃣'), ('5', '5️⃣'), ('6', '6️⃣'), ('7', '7️⃣'), ('8', '8️⃣'), ('9', '9️⃣'), ('10', '🔟')], default='1', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='donecheck',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
