# Generated by Django 3.1.2 on 2020-12-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20201223_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasku',
            name='donecheck',
        ),
        migrations.AddField(
            model_name='task',
            name='donecheck',
            field=models.BooleanField(default=False),
        ),
    ]
