# Generated by Django 3.1.2 on 2020-12-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
